"""change description

Revision ID: 1ebf3d0e7ee4
Revises: 20260609_0001
Create Date: 2026-06-14 06:39:46.328386+00:00
"""

from __future__ import annotations

revision = "1ebf3d0e7ee4"
down_revision = "20260609_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
